version: '3'

services:
  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: hello
      MYSQL_USER: hello
      MYSQL_PASSWORD: hello-pw
      MYSQL_ROOT_PASSWORD: my-root-pw
    command:
      - 'mysqld'
      - '--default-authentication-plugin=mysql_native_password'
